version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # DATABASE_URL: postgresql://postgres:password@db/fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
